syntax = "proto3";

package com.example.sidecar;

option java_package = "com.example.sidecar";
option java_multiple_files = true;

service SidecarService {
  rpc Ping(PingRequest) returns (PingResponse);
  rpc ReadRows(ReadRowsRequest) returns (stream SidecarRow);
  rpc MutateRow(MutateRowRequest) returns (MutateRowResponse);
  rpc MutateRows(MutateRowsRequest) returns (MutateRowsResponse);
  rpc GetStats(StatsRequest) returns (StatsResponse);
}

message MutateRowRequest {
  bytes request_bytes = 1; // Serialized com.google.bigtable.v2.MutateRowRequest
}

message MutateRowResponse {}

message MutateRowsRequest {
  bytes request_bytes = 1; // Serialized com.google.bigtable.v2.MutateRowsRequest
}

message MutateRowsResponse {
  repeated MutateRowsEntry entries = 1;
}

message MutateRowsEntry {
  int32 index = 1;
  int32 status_code = 2;
  string status_message = 3;
}

message StatsRequest {}

message StatsResponse {
  int64 read_rows_count = 1;
}

message PingRequest {
  string message = 1;
}

message PingResponse {
  string message = 1;
}

message ReadRowsRequest {
  bytes request_bytes = 1; // Serialized com.google.bigtable.v2.ReadRowsRequest
}

message SidecarRow {
  bytes key = 1;
  repeated SidecarFamily families = 2;
}

message SidecarFamily {
  string name = 1;
  repeated SidecarColumn columns = 2;
}

message SidecarColumn {
  bytes qualifier = 1;
  repeated SidecarCell cells = 2;
}

message SidecarCell {
  bytes value = 1;
  int64 timestamp_micros = 2;
  repeated string labels = 3;
}
