# Copyright 2018 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require "bundler/setup"
require "bundler/gem_tasks"
require "tmpdir"

namespace :proto do
  desc "Regenerate Ruby protos from sidecar.proto"
  task :generate do
    proto_file = File.join(__dir__, "sidecar", "src", "main", "proto", "sidecar.proto")
    output_dir = File.join(__dir__, "lib", "google", "cloud", "bigtable", "sidecar_proto")
    
    puts "Regenerating Ruby protos from #{proto_file}..."
    sh "grpc_tools_ruby_protoc -I #{File.dirname(proto_file)} --ruby_out=#{output_dir} --grpc_out=#{output_dir} #{proto_file}"
  end
end

namespace :sidecar do
  desc "Build the Java sidecar jlink runtime (hybrid) and copy it to the gem lib directory"
  task :build => "proto:generate" do
    java_dir = File.join(__dir__, "sidecar")
    runtime_source = File.join(java_dir, "jlink-runtime")
    runtime_target = File.join(__dir__, "lib", "google", "cloud", "bigtable", "runtime")

    puts "Building Java sidecar fat JAR..."
    Dir.chdir(java_dir) do
      sh "mvn clean package"
      
      if Dir.exist? "jlink-runtime"
        puts "jlink-runtime already exists, skipping jlink creation."
      else
        puts "Creating jlink runtime (JRE only)..."
        jlink_bin = "/usr/lib/jvm/java-17-openjdk-amd64/bin/jlink"
        jmods_path = "/usr/lib/jvm/java-17-openjdk-amd64/jmods"
        
        # Modules identified by jdeps + some extras for safety
        modules = [
          "java.base", "java.compiler", "java.management", "java.naming",
          "java.security.jgss", "java.sql", "jdk.unsupported", "java.logging",
          "java.xml", "java.desktop", "jdk.crypto.ec", "java.instrument"
        ].join(",")

        sh "#{jlink_bin} --module-path #{jmods_path} " \
           "--add-modules #{modules} " \
           "--output jlink-runtime " \
           "--no-header-files --no-man-pages --compress=2"
      end

      puts "Copying fat JAR and creating launcher..."
      jar_name = "java-sidecar-1.0-SNAPSHOT-jar-with-dependencies.jar"
      mkdir_p "jlink-runtime/app"
      cp "target/#{jar_name}", "jlink-runtime/app/sidecar.jar"

      launcher_path = "jlink-runtime/bin/sidecar-launcher"
      File.open(launcher_path, "w") do |f|
        f.puts "#!/bin/sh"
        f.puts "DIR=$(dirname \"$0\")"
        f.puts "exec \"$DIR/java\" $BIGTABLE_SIDECAR_JVM_FLAGS -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -jar \"$DIR/../app/sidecar.jar\" \"$@\""
      end
      chmod 0755, launcher_path
    end

    puts "Syncing jlink runtime to #{runtime_target}..."
    rm_rf runtime_target
    mkdir_p File.dirname(runtime_target)
    cp_r runtime_source, runtime_target
  end
end

namespace :verify do
  desc "Build, install, and verify the gem."
  task :install => "sidecar:build" do
    gem_name = "google-cloud-bigtable"
    version = File.read("lib/google/cloud/bigtable/version.rb").match(/VERSION = "([^"]+)"/)[1]
    gem_file = "#{gem_name}-#{version}.gem"

    # Build the gem
    sh "gem build #{gem_name}.gemspec"

    # Use a persistent directory for installation to speed up iterations
    # by avoiding rebuilding native extensions every time.
    dir = File.expand_path("tmp/verify_gems", __dir__)
    mkdir_p dir
    
    puts "Verifying installation in #{dir}..."
    
    # Install the gem into the directory
    sh "gem install #{gem_file} --install-dir #{dir} --no-document"
    
    # Also install minitest if not present
    sh "gem install minitest --install-dir #{dir} --no-document"

    # Run a verification script using the installed gem
    # We set GEM_HOME to the directory so 'require' finds our installed gem
    env = { "GEM_HOME" => dir, "GEM_PATH" => dir }
    Bundler.with_unbundled_env do
      sh env, "ruby test/google/cloud/bigtable/sidecar_integration_test.rb"
    end

    # Clean up the built gem file
    rm gem_file
  end
end

# Make sure sidecar is built before building the gem
task build: "sidecar:build"

require "rubocop/rake_task"
RuboCop::RakeTask.new

require "rake/testtask"
desc "Run tests."
Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList["test/**/*_test.rb"]
  t.warning = false
end

namespace :test do
  desc "Runs tests with coverage."
  task :coverage do
    require "simplecov"
    SimpleCov.start do
      command_name "google-cloud-bigtable"
      track_files "lib/**/*.rb"
      add_filter "lib/google/cloud/bigtable/admin/v2/doc"
      add_filter "lib/google/cloud/bigtable/v2/doc"
      add_filter "test/"
    end

    Rake::Task[:test].invoke
  end
end

# Acceptance tests
desc "Run the google-cloud-bigtable acceptance tests."
task :acceptance, :project, :keyfile do |_t, args|
  project = args[:project]
  project ||= ENV["BIGTABLE_TEST_PROJECT"] || ENV["GCLOUD_TEST_PROJECT"]
  keyfile = args[:keyfile]
  keyfile ||= ENV["BIGTABLE_TEST_KEYFILE"] || ENV["GCLOUD_TEST_KEYFILE"]

  keyfile ||= ENV["BIGTABLE_TEST_KEYFILE_JSON"] || ENV["GCLOUD_TEST_KEYFILE_JSON"] unless keyfile

  if project.nil? || keyfile.nil?
    raise "You must provide a project and keyfile. e.g. rake acceptance[test123, /path/to/keyfile.json] or " \
          "BIGTABLE_TEST_PROJECT=test123 BIGTABLE_TEST_KEYFILE=/path/to/keyfile.json rake acceptance"
  end

  # clear any env var already set
  require "google/cloud/bigtable/credentials"
  Google::Cloud::Bigtable::Credentials.env_vars.each do |path|
    ENV[path] = nil
  end

  # always overwrite when running tests
  ENV["BIGTABLE_PROJECT"] = project
  ENV["BIGTABLE_KEYFILE_JSON"] = keyfile

  Rake::Task["acceptance:run"].invoke
end

namespace :acceptance do
  Rake::TestTask.new :run do |t|
    t.libs << "acceptance"
    t.test_files = FileList["acceptance/**/*_test.rb"]
    t.warning = false
  end

  desc "Run acceptance tests with coverage."
  task :coverage, :project, :keyfile do |_t, args|
    require "simplecov"
    SimpleCov.start do
      command_name "google-cloud-bigtable"
      track_files "lib/**/*.rb"
      add_filter "lib/google/cloud/bigtable/admin/v2/doc"
      add_filter "lib/google/cloud/bigtable/v2/doc"
      add_filter "acceptance/"
    end

    Rake::Task[:acceptance].invoke args[:project], args[:keyfile]
  end

  desc "Run acceptance cleanup."
  task :cleanup do |_t, args|
    project = args[:project]
    project ||= ENV["BIGTABLE_TEST_PROJECT"] || ENV["GCLOUD_TEST_PROJECT"]

    keyfile = args[:keyfile]
    keyfile ||= ENV["BIGTABLE_TEST_KEYFILE"] || ENV["GCLOUD_TEST_KEYFILE"]

    keyfile ||= ENV["BIGTABLE_TEST_KEYFILE_JSON"] || ENV["GCLOUD_TEST_KEYFILE_JSON"] unless keyfile

    if project.nil? || keyfile.nil?
      raise "You must provide a project and keyfile. e.g. rake acceptance[test123, /path/to/keyfile.json] or " \
            "BIGTABLE_TEST_PROJECT=test123 BIGTABLE_TEST_KEYFILE=/path/to/keyfile.json rake acceptance"
    end

    # clear any env var already set
    require "google/cloud/bigtable/credentials"
    Google::Cloud::Bigtable::Credentials.env_vars.each do |path|
      ENV[path] = nil
    end

    # always overwrite when running tests
    ENV["BIGTABLE_PROJECT"] = project
    ENV["BIGTABLE_KEYFILE_JSON"] = keyfile

    $LOAD_PATH.unshift "lib"
    require "google/cloud/bigtable"
    puts "Cleaning up Bigtable instances and databases."

    gcloud = Google::Cloud.new
    bigtable = gcloud.bigtable
    bigtable.instances.each do |instance|
      instance.delete
    rescue StandardError => e
      puts "Error while cleaning up #{instance.instance_id} instance.\n\n#{e}"
    end
  end
end

task :samples do
  Rake::Task["samples:latest"].invoke
end

namespace :samples do
  task :latest do
    if File.directory? "samples"
      Dir.chdir "samples" do
        Bundler.with_unbundled_env do
          ENV["GOOGLE_CLOUD_SAMPLES_TEST"] = "not_master"
          sh "bundle update"
          sh "bundle exec rake test"
        end
      end
    else
      puts "The google-cloud-bigtable gem has no samples to test."
    end
  end

  task :master do
    if File.directory? "samples"
      Dir.chdir "samples" do
        Bundler.with_unbundled_env do
          ENV["GOOGLE_CLOUD_SAMPLES_TEST"] = "master"
          sh "bundle update"
          sh "bundle exec rake test"
        end
      end
    else
      puts "The google-cloud-bigtable gem has no samples to test."
    end
  end
end

require "yard"
require "yard/rake/yardoc_task"
YARD::Rake::YardocTask.new do |y|
  # y.options << "--fail-on-warning"
end

desc "Run yard-doctest example tests."
task :doctest do
  sh "bundle exec yard config load_plugins true && bundle exec yard doctest"
end

desc "Run rubocop on yard examples."
task :rubocop_yard_examples do
  YARD.parse "lib/**/*.rb"
  registry = YARD::Registry.load_all
  examples = registry.all.map { |object| object.tags :example }.flatten

  dir_name = "rubocop_yard_examples"
  rm_rf dir_name
  mkdir_p dir_name
  hsh = examples.each_with_object({}) do |e, h|
    obj = e.object
    name = "#{obj.file.gsub(/\W/, '_')}_#{obj.line}"
    h[name] ||= []
    h[name] << e.text
  end
  hsh.each_pair do |k, v|
    v.each_with_index do |text, i|
      file_name = i.positive? ? "#{k}_#{i + 1}" : k # "foo", "foo_2", "foo_3", ...
      File.write "#{dir_name}/#{file_name}.rb", text
    end
  end
  sh "bundle exec rubocop #{dir_name} --config .rubocop_yard_examples.yml"
end

desc "Start an interactive shell."
task :console do
  require "irb"
  require "irb/completion"

  $LOAD_PATH.unshift "lib"

  require "google-cloud-bigtable"
  def gcloud
    @gcloud ||= Google::Cloud.new
  end

  ARGV.clear
  IRB.start
end

desc "Run the CI build"
task :ci do
  header "BUILDING google-cloud-bigtable"
  header "google-cloud-bigtable rubocop", "*"
  Rake::Task[:rubocop].invoke
  header "google-cloud-bigtable yard", "*"
  header "bigtable yard still had warnings", "!"
  Rake::Task[:yard].invoke
  header "google-cloud-bigtable doctest", "*"
  Rake::Task[:doctest].invoke
  header "google-cloud-bigtable test", "*"
  Rake::Task[:test].invoke
end

namespace :ci do
  desc "Run the CI build, with acceptance tests."
  task :acceptance do
    Rake::Task[:ci].invoke
    header "google-cloud-bigtable acceptance", "*"
    Rake::Task[:acceptance].invoke
  end
  task :a do
    # This is a handy shortcut to save typing
    Rake::Task["ci:acceptance"].invoke
  end
end

task default: :test

def header str, token = "#"
  line_length = str.length + 8
  puts ""
  puts token * line_length
  puts "#{token * 3} #{str} #{token * 3}"
  puts token * line_length
  puts ""
end
