# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sidecar.proto

require 'google/protobuf'


descriptor_data = "\n\rsidecar.proto\x12\x13\x63om.example.sidecar\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"2\n\x0fReadRowsRequest\x12\x10\n\x08table_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"O\n\nSidecarRow\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\x34\n\x08\x66\x61milies\x18\x02 \x03(\x0b\x32\".com.example.sidecar.SidecarFamily\"R\n\rSidecarFamily\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x33\n\x07\x63olumns\x18\x02 \x03(\x0b\x32\".com.example.sidecar.SidecarColumn\"S\n\rSidecarColumn\x12\x11\n\tqualifier\x18\x01 \x01(\x0c\x12/\n\x05\x63\x65lls\x18\x02 \x03(\x0b\x32 .com.example.sidecar.SidecarCell\"F\n\x0bSidecarCell\x12\r\n\x05value\x18\x01 \x01(\x0c\x12\x18\n\x10timestamp_micros\x18\x02 \x01(\x03\x12\x0e\n\x06labels\x18\x03 \x03(\t2\xb2\x01\n\x0eSidecarService\x12K\n\x04Ping\x12 .com.example.sidecar.PingRequest\x1a!.com.example.sidecar.PingResponse\x12S\n\x08ReadRows\x12$.com.example.sidecar.ReadRowsRequest\x1a\x1f.com.example.sidecar.SidecarRow0\x01\x42\x17\n\x13\x63om.example.sidecarP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Com
  module Example
    module Sidecar
      PingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.example.sidecar.PingRequest").msgclass
      PingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.example.sidecar.PingResponse").msgclass
      ReadRowsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.example.sidecar.ReadRowsRequest").msgclass
      SidecarRow = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.example.sidecar.SidecarRow").msgclass
      SidecarFamily = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.example.sidecar.SidecarFamily").msgclass
      SidecarColumn = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.example.sidecar.SidecarColumn").msgclass
      SidecarCell = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.example.sidecar.SidecarCell").msgclass
    end
  end
end
