# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: sidecar.proto for package 'com.example.sidecar'

require 'grpc'
require 'sidecar_pb'

module Com
  module Example
    module Sidecar
      module SidecarService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'com.example.sidecar.SidecarService'

          rpc :Ping, ::Com::Example::Sidecar::PingRequest, ::Com::Example::Sidecar::PingResponse
          rpc :ReadRows, ::Com::Example::Sidecar::ReadRowsRequest, stream(::Com::Example::Sidecar::SidecarRow)
          rpc :MutateRow, ::Com::Example::Sidecar::MutateRowRequest, ::Com::Example::Sidecar::MutateRowResponse
          rpc :MutateRows, ::Com::Example::Sidecar::MutateRowsRequest, ::Com::Example::Sidecar::MutateRowsResponse
          rpc :GetStats, ::Com::Example::Sidecar::StatsRequest, ::Com::Example::Sidecar::StatsResponse
          rpc :ClearStats, ::Com::Example::Sidecar::ClearStatsRequest, ::Com::Example::Sidecar::ClearStatsResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
